language: php

dist: trusty
sudo: false

php:
  - 7.3
  - 7.2
  - 7.1
  - nightly

env:
  matrix:
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm-nightly

install:
  - if [[ "$DEPENDENCIES" = 'high' ]]; then travis_retry composer update --no-interaction --prefer-stable; fi
  - if [[ "$DEPENDENCIES" = 'low' ]]; then travis_retry composer update --no-interaction --prefer-stable --prefer-lowest; fi

before_script:
  - if [[ "$DEPENDENCIES" = 'low' ]]; then export PHP_ARGS=$(php -r "echo '-d error_reporting=', E_ALL ^ (E_DEPRECATED | E_USER_DEPRECATED);"); else export PHP_ARGS=''; fi

script:
  - php ${PHP_ARGS} vendor/bin/phpunit

after_script:
  - venodr/bin/php-coveralls --exclude-group functional
