#!/usr/bin/env php
<?php

declare(strict_types=1);

/*
 * This file is part of the php-header-file/php-header-file package.
 *
 * (c) Bartłomiej Krukowski <bartlomiej@krukowski.me>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use PhpHeaderFile\ApplicationFactory;

$autoloaderExists = false;
foreach (['/../../autoload.php', '/../vendor/autoload.php', '/vendor/autoload.php'] as $path) {
    $file = __DIR__.$path;
    if (\file_exists($file)) {
        require $file;
        $autoloaderExists = true;

        break;
    }
}

if (!$autoloaderExists) {
    \fwrite(\STDERR, "File 'vendor/autoload.php' not found\n");
    exit(1);
}

(new ApplicationFactory())->createApp()->run();
